// RPCZ examples
[
{ "proto_library": {
    "name": "search_proto",
    "sources": [ "common/search.proto" ]
} },
{ "cc_binary": {
    "name": "example_client",
    "cc_headers": [ "cpp/example_client.cc" ]
} }
]